apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: misiukpipelinessampleapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: misiukpipelinessampleapp 
    spec:
      containers:
        - name: misiukpipelinessampleapp 
          image: tectocomacr.azurecr.io/misiukpipelinessampleapp
          ports:
          - containerPort: 8080